name: Feature Request
description: Suggest a new feature or enhancement for ARI
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests help ARI grow. Please describe your idea clearly.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Is it frustration with something?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you'd like to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other solutions or features you've considered?

  - type: dropdown
    id: layer
    attributes:
      label: Affected Layer
      multiple: true
      options:
        - "L0 Cognitive"
        - "L1 Kernel"
        - "L2 System"
        - "L3 Agents"
        - "L4 Strategic"
        - "L5 Execution"
        - "L6 Interfaces"
        - "New / Cross-cutting"

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - "Small (< 1 day)"
        - "Medium (1-3 days)"
        - "Large (1+ week)"
        - "Unknown"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or references
